### ISSUE TITLE
Firefox for Android: once images are disabled it is not possible to enable them again

### ISSUE THREAD

**Issue by PolarGoose** [ckuhl/ImageBlockX#11]
### How to reproduce:
1. Start Firefox for Android with "ImageBlockX" plugin installed
2. Open any website with images
3. Go to "three dots" menu (the top right corner) and click "Images are allowed"
4. Refresh the website, images are blocked.
5. In "three dots" menu click "Images are blocked"
6. Refresh the website, images are still blocked but should be allowed and the the button in "three dots" menu always shows "Images are blocked"

### System information:
- Firefox for android 57.0.4
- Android 7.1.2

### Workaround if this issue occurs:
- Restart Firefox or disable and enable again "ImageBlockX" addon

**Comment by PolarGoose** [comment]
there is also a comment from @ohhai on this issue:
https://github.com/ckuhl/ImageBlockX/issues/6#issuecomment-352451072

**Comment by ckuhl** [comment]
Sorry for the delay! Are you still having these issues? And if so, what version of ImageBlockX are you on? Can you determine that from inside Firefox?

**Comment by PolarGoose** [comment]
> Are you still having these issues?

yes

> what version of ImageBlockX are you on?

0.3.1

**Comment by ohhai** [comment]
Still have. Addon v0.3, FF 59.0.2

**Comment by ckuhl** [comment]
Hmm, I looked into it and it looks like I've messed up something with saving / loading permissions. I'll have to dig into after Easter when I can get a free weekend.

**Comment by ckuhl** [comment]
I have a feeling this is the same as issue #10, so for now I'm going to close this.

**Comment by PolarGoose** [comment]
@ckuhl, no, this issue is the same as: [On Mozilla portable, once disabled the images are always disabled](https://github.com/ckuhl/ImageBlockX/issues/7).
The https://github.com/ckuhl/ImageBlockX/issues/10 is about different problem
