### ISSUE TITLE
Images are shown when starting firefox, although the add-on was toggled off previously

### ISSUE THREAD

**Issue by farshad007** [ckuhl/ImageBlockX#12]
Hi

Thanks for this very useful add-on.
Sadly there is sth wrong with it.
Images are shown when starting firefox, despite of toggled off setting in the previous session, so retoggling is necessary.
Is there a solution to it?

Cheers
Farshad

**Comment by ckuhl** [comment]
Hi @farshad007 , I've made some changes since you created this issue. Are you are still having the same problem?

**Comment by PolarGoose** [comment]
This issue is the same as already existing one: [The addon shows that images are blocked, but they are allowed](https://github.com/ckuhl/ImageBlockX/issues/10)
