### ISSUE TITLE
[wishlist] please use more contrast button icon

### ISSUE THREAD

**Issue by ohhai** [ckuhl/ImageBlockX#8]
Current button image is dark and is hardly recognized with dark FF themes.
Any universal style would be better (just white outline might be enough).

**Comment by ckuhl** [comment]
That's a good idea! I will definitely look into doing that when I have some time. Or if you're up to the challenge, you could try creating it yourself?

**Comment by ohhai** [comment]
Do you have a vectorized image for the icon? I see only raster/png version in the repo.
Adding outline for vector objects should be the simplest.

**Comment by ckuhl** [comment]
The original image is from [ionicons](https://github.com/ionic-team/ionicons/blob/master/src/image.svg).

The X I just pasted on top in like GIMP I think, so there's no vector at all of that (sorry!).

**Comment by ohhai** [comment]
That's OK. Did this, will prepare a pull request tomorrow if fine:

![image svg](https://user-images.githubusercontent.com/3885783/33959087-129aff4e-e04f-11e7-81b3-0a0e2177fa13.png)

**Comment by ohhai** [comment]
BTW, it might be better to have an svg source in the tree and generate pngs in runtime. However, it will create a build dependency on something like imagemagick.
As an alternative I can create png versions manually and place original svg just beside them.

**Comment by ckuhl** [comment]
I'm okay just including the svg - it's no big deal to add depends for development in my opinion.

**Comment by ohhai** [comment]
OK, so I'll prepare a patch with all png images removed and added svg with some makefile rules to generate png.

**Comment by ohhai** [comment]
Have some patch, want to verify but can't (re)install the addon from make-generated zip. Tried install from file at FF addons page, but it tells the file is corrupted.
Also can't replace .xpi file in profile/extensions folder—FF just deletes it on startup.
It expects some manifest or signature, maybe.
Can it be verified locally?

**Comment by ckuhl** [comment]
If you go to `about:debugging` in ff you can load temporary extensions - is that would you're looking for?

**Comment by ohhai** [comment]
Yes, it helps, thanks a lot!
One more question: I use compact FF theme and icon size is smaller than 32x32 here. 32 px is minimal size in ImageBlockX/icons currently. Should it also have something like 16x16, 24x24, etc?
It's downscaled anyway but it might save several bytes of RAM...
There is a big variety of icon sizes in other addons, there might be some guidelines from Mozilla, but I'm not sure.

**Comment by ckuhl** [comment]
[MDN says](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/icons) that you can give any number of icons, and recommends providing a 48x48 px icon as a default. I'll leave it to your discretion how many and what sizes should be chosen 👍

**Comment by ohhai** [comment]
OK, I just add 16x16 and 24x24 and let FF decide.
Created pull request (hope did it right). It's not a piece of art, feel free to manipulate svg.
"X" letter is left as font (not vector object) so you can even change the typeface.
Png file names are hardcoded. I'm sure there is a smarter way to iterate just over sizes.
Any feedback is welcome.
